name: mockable_filesystem
version: 0.0.3
author: Dart Team <misc@dartlang.org>
description: Provides a FileSystem factory class for allocating File, Directory and Link objects, with two implementations - one which in turn returns the real objects from dart:io, and one which returns mock versions. This allows  tests to be written that make use of files and directories without having to create them on disk. The mock File/Directory/Link classes are not complete, but have sufficient functionality to work in most cases. The ultimate aim is to have complete mock implementations, as well as the  ability to mock Windows file systems on Linux/Mac and vice-versa, to help  with testing code for cross-platform correctness.
homepage: https://github.com/dart-lang/mockable_filesystem
dependencies:
  logging: ">=0.6.5"
  path: ">=0.6.5"
dev_dependencies:
  logging: ">=0.6.5"
  mockable_filesystem: ">=0.0.1"
  path: ">=0.6.5"
  unittest: ">=0.6.5"
